### PR TITLE
Modularized the codebase using webpack

### PR DESCRIPTION
**Pull request by jrdrg**
I added a build step to the project to use webpack. This will make it more modularized and easier for newer developers to pick up and add code. 

Right now the entire application is contained in one .js file - this is really not optimal and especially for new developers it will cause bad habits if they aren't already familiar with good coding practices. 

This pull request introduces one extra step when developing (install node.js and run gulp) but I think the benefits are worth it, since a new developer can easily find a small module to work on and add the required functionality, rather than searching around in one super huge monolithic file. Also, when adding new third-party libs they can be 'require'd rather than having to include a separate script tag for each one, which makes it easier. If the application js file gets too large, webpack also supports splitting into chunks that can be loaded separately and/or async as required.

### CODE REVIEW

**Comment by raynor85** [comment]
It is great, and I agree with you about the need of introducing an extra
tool to automate. In the beginning I was thinking of grunt and bower, but I
think your solution is valid as well. If you want before merging everything
I can provide you the splitted js which compose the ugly application.js
file and the scss files as well, so you can integrate everything with
webpack.

**Comment by jrdrg** [comment]
Sure, that sounds good - I should have some time tomorrow or Monday to make another commit with those changes.

**Comment by raynor85** [comment]
Here the Blue Economics project before the php integration and the
MIddleMan removing. In the source folder you can find the js and the scss
which compose the actual files (only the model.js is missing, but it is
already splitted from the application.js so you don't need it). Let me know
if everything is clear. Have a nice one!

Ruben

2015-06-21 4:01 GMT+02:00 John Rodriguez notifications@github.com:

**Comment by jrdrg** [comment]
I don't see the source files anywhere, did you forget a link or am I missing something? =)

**Pull request merged**
